### PR TITLE
Replace `default` with `example` in OpenAPI

### PR DESCRIPTION
**Pull request by RReverser**
`default` implies a default value that will be used if parameter is not provided, but the parameters are all mandatory and values like `ClientID=123` are certainly not defaults.

Instead, a better field to use is `example` which still sets this value for input fields in the Swagger UI but removes the "Default value: ..." text.

It's also a better hint for tooling so that it doesn't autogenerate functions with optional parameters set to these values.

### CODE REVIEW

**Comment by Peter-Simpson** [comment]
Merged as suggested, I should probably at a minimum value of 1 for the BinX and BinY properties.

**Comment by RReverser** [comment]
> Merged as suggested, I should probably at a minimum value of 1 for the BinX and BinY properties.

Did you mean add? Yes, a good idea.

**Comment by Peter-Simpson** [comment]
Yes, I've added "minimum: 1" to Camera.BinX, BinY, MaxBinX and MaxBinY, I've committed the change to the main branch.

The updated version, including your PRs, is [here](https://ascom-standards.org/api7).

**Comment by RReverser** [comment]
Thanks. Looking at the published version, if seems there were some rebase artifacts, eg minimum/maximum was reintroduced for device_number again: https://github.com/ASCOMInitiative/ASCOMRemote/blob/16d34dfaefe786f4a02e1acfad8202f1f3a5ebe5/Swagger/AlpacaDeviceAPI_v1.yaml#L5849

**Comment by Peter-Simpson** [comment]
OK, I'll have a look this evening, the Github resolve conflict dialogue only showed me one conflict, which I fixed.  I'll review the changes and fix the reversions.

**Comment by RReverser** [comment]
No problem. Might be worth taking a look at https://github.com/ASCOMInitiative/ASCOMRemote/issues/67 for the next update as well.

**Comment by Peter-Simpson** [comment]
I reviewed the changes from both of your PRs and only found the device_number reversion, which I fixed it in the commit above.

**Pull request merged**
