### PR TITLE
Various OpenAPI improvements

### PR DESCRIPTION
**Pull request by RReverser**
Something I wanted to do during my last streak of Alpaca's OpenAPI PRs is use named enums instead of having all those `0 = variant1, 1 = variant2, ...` manual descriptions in plain text.

Unfortunately, before OpenAPI 3.1 this was only possible to do via 3rd-party plugins - which I didn't want to tie Alpaca's OpenAPI definition to. Then it became possible to do via `const` + `oneOf` as described [here](https://stackoverflow.com/a/66471626/439965), but Swagger UI didn't support those definitions yet.

Now that Swagger UI has implemented missing fetaures, everything has finally snapped in place.

This PR:
 - Upgrades Swagger UI (using a CDN link this time instead of keeping copies in the repo, as that seems wasteful).
 - Changes logo insertion to use the plugin system (which should be more robust to upgrades than patching DOM).
 - Updates `.yaml` reference in `index.html` to point to a relative path instead of an absolute URL for easier development.
 - Adds named enums with descriptions copied from the ASCOM docs to `schemas` and `responses` where appropriate, removing text from the description.
 - Improves `imagearray` and `imagearrayvariant` responses:
	 - Improved Markdown formatting for array blocks.
	 - Marked `imagearray`'s `Type` field as `const: 2` to make it explicit that it's always the same.
	 - Made their responses use `oneOf` to represent both 2D and 3D arrays (previously it erroneously only represented a 2D array) and tying them to a corresponding `Rank` value.
 - Declared few more reusable schemas with `minimum`, `maximum` limits and date formats.

Some motivational screenshots before/after:

---

Before:
image

After:
image

---

Before:
image

After:
image

---

Before:
image

After:
image

### CODE REVIEW

**Review by Peter-Simpson — COMMENTED** [review]
Thanks Ingvar, the CDN download is a lot easier than manually updating CSS.

I've loaded the files to [ASCOM-Standards](https://ascom-standards.org/apitest) and they seem to be working OK.

The ErrorNumber display is complex: "Integer (Integer | Number | Integer)" and I am concerned that it will confuse less experienced users. Is it possible to simplify it?  

Yes, in JSON all integers are numbers, but there will never be a non-integer number in this field, so the reference to number feels misleading. Can it just say Integer?

image

Otherwise it looks very good and a lot more colourful! I'll keep checking.

**Comment by RReverser** [comment]
> The ErrorNumber display is complex: "Integer (Integer | Number | Integer)" and I am concerned that it will confuse less experienced users. Is it possible to simplify it?

Fixed with a simple work around, so now it prints it as `integer | (integer | integer)`.

**Comment by RReverser** [comment]
Ideally, I wish it also would deduplicate same types in that list instead of listing them over and over, but, sadly this is something that would have to be fixed in Swagger itself.

That said, it should be fairly easy to completely hide this field altogether with CSS. I figure the `format` (`int32` / `uint32`) should be self-describing enough, and less confusing than showing both `integer | (integer | integer)` and `int32`?

**Comment by RReverser** [comment]
Just added said CSS. I think this looks much cleaner:

image

**Comment by RReverser** [comment]
One more small tweak - made constants have the same style as range constraints so that they're easier to spot.

image

**Comment by Peter-Simpson** [comment]
Thanks Ingvar, that looks so much better and cleaner, I'll merge the branch and add the Platform 7 changes.

**Comment by RReverser** [comment]
> Just added said CSS. I think this looks much cleaner:

Only just noticed that this change also hid types like `string` as they don't have a fallback custom `format` to show. That's not ideal, I'm going to fix it in a follow-up PR in a second.

**Pull request merged**
